metadata:
  name: external
  namespace: demo
  annotations:
    # Attaches the Certificate Manager map. GKE reads this annotation and configures the HTTPS listener's certificates from it.
    networking.gke.io/certmap: k8-lab-gateway-cert-map
spec:
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same

    - name: https
      protocol: HTTPS
      port: 443
      allowedRoutes:
        namespaces:
          from: Same